namespace NeoDatis.Odb
{
	/// <summary>The interface to represent OID.</summary>
	/// <remarks>
	/// The interface to represent OID. OID is a unique identifier for NeoDatis ODB
	/// entities like objects and classes. The id is generated by NeoDatis
	/// </remarks>
	/// <author>osmadja</author>
	public interface OID : System.IComparable
	{
		long GetClassId();

		long GetObjectId();

		int GetType();

		/// <summary>To retrieve a string representation of an OID</summary>
		/// <returns></returns>
		string OidToString();
	}
}
