namespace NeoDatis.Odb.Impl.Core.Btree
{
	/// <summary>The NeoDatis ODB BTree.</summary>
	/// <remarks>The NeoDatis ODB BTree. It extends the DefaultBTree implementation to add the ODB OID generated by the ODB database.
	/// 	</remarks>
	/// <author>osmadja</author>
	[System.Serializable]
	public class ODBBTreeMultiple : NeoDatis.Btree.Impl.Multiplevalue.BTreeMultipleValuesPerKey
	{
		public ODBBTreeMultiple() : base()
		{
		}

		public ODBBTreeMultiple(string name, int degree, NeoDatis.Btree.IBTreePersister persister
			) : base(name, degree, persister)
		{
		}

		protected NeoDatis.Odb.OID oid;

		public override NeoDatis.Btree.IBTreeNode BuildNode()
		{
			return new NeoDatis.Odb.Impl.Core.Btree.ODBBTreeNodeMultiple(this);
		}

		public override object GetId()
		{
			return oid;
		}

		public override void SetId(object id)
		{
			this.oid = (NeoDatis.Odb.OID)id;
		}
	}
}
